/*
 * RCC.h
 *
 *  Created on: May 1, 2025
 *      Author: erhan
 */

#ifndef INC_RCC_H_
#define INC_RCC_H_

#include "stm32f407xx.h"

/*
 * RCC AHB1 Peripherals Clock Control Macro Definitions
 *
 */

#define RCC_AHB1_CLK_EN(PERIPH)		do{ uint32_t tempValue = 0;										\
										SET_BIT(RCC->AHB1ENR, PERIPH);								\
										tempValue = READ_BIT(RCC->AHB1ENR, PERIPH);					\
										UNUSED(tempValue);											\
									}while(0)

#define RCC_GPIOA_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOAEN)
#define RCC_GPIOB_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOBEN)
#define RCC_GPIOC_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOCEN)
#define RCC_GPIOD_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIODEN)
#define RCC_GPIOE_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOEEN)
#define RCC_GPIOF_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOFEN)
#define RCC_GPIOG_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOGEN)
#define RCC_GPIOH_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOHEN)
#define RCC_GPIOI_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOIEN)
#define RCC_GPIOJ_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOJEN)
#define RCC_GPIOK_CLK_EN()			RCC_AHB1_CLK_EN(RCC_AHB1ENR_GPIOKEN)

#define RCC_GPIOA_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN)
#define RCC_GPIOB_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN)
#define RCC_GPIOC_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN)
#define RCC_GPIOD_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN)
#define RCC_GPIOE_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOEEN)
#define RCC_GPIOF_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOFEN)
#define RCC_GPIOG_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOGEN)
#define RCC_GPIOH_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOHEN)
#define RCC_GPIOI_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOIEN)
#define RCC_GPIOJ_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOJEN)
#define RCC_GPIOK_CLK_DIS()			CLEAR_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOKEN)

#endif /* INC_RCC_H_ */
