/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"

static void GPIO_LedConfig();

int main(void)
{
	RCC_GPIOD_CLK_EN();
	GPIO_LedConfig();
	while(1)
	{
		GPIO_Write_Pin(GPIOD, GPIO_PIN_12, GPIO_PIN_SET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_13, GPIO_PIN_SET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_13, GPIO_PIN_RESET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET);
		for(uint32_t counter = 0; counter < 999999; counter++);
		GPIO_Write_Pin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET);
		for(uint32_t counter = 0; counter < 999999; counter++);
	}
    /* Loop forever */
	for(;;);
}

static void GPIO_LedConfig()
{
	GPIO_InitTypeDef ledConfig = {0};

	ledConfig.pinNumber = GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
	ledConfig.Mode = GPIO_MODE_OUTPUT;
	ledConfig.Otype = GPIO_OTYPE_PP;
	ledConfig.PuPd = GPIO_PUPDR_NOPULL;
	ledConfig.Speed = GPIO_OSPEED_HIGH;

	GPIO_Init(GPIOD, &ledConfig);
}
