/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"

int main(void)
{
	RCC_GPIOA_CLK_EN();
	GPIO_WritePin(GPIOA, GPIO_PIN_0 | GPIO_PIN_1, GPIO_PIN_SET);
	RCC_GPIOB_CLK_EN();
	RCC_GPIOC_CLK_EN();
	RCC_GPIOD_CLK_EN();
	RCC_GPIOE_CLK_EN();
	RCC_GPIOF_CLK_EN();
	RCC_GPIOG_CLK_EN();
	RCC_GPIOH_CLK_EN();
	RCC_GPIOI_CLK_EN();
	RCC_GPIOJ_CLK_EN();
	RCC_GPIOK_CLK_EN();



	RCC_GPIOA_CLK_DIS();
	RCC_GPIOB_CLK_DIS();
	RCC_GPIOC_CLK_DIS();
	RCC_GPIOD_CLK_DIS();
	RCC_GPIOE_CLK_DIS();
	RCC_GPIOF_CLK_DIS();
	RCC_GPIOG_CLK_DIS();
	RCC_GPIOH_CLK_DIS();
	RCC_GPIOI_CLK_DIS();
	RCC_GPIOJ_CLK_DIS();
	RCC_GPIOK_CLK_DIS();
    /* Loop forever */
	for(;;);
}
